// Code generated by protoc-gen-go. DO NOT EDIT.
// source: extend.proto

package rest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HttpMethod int32

const (
	HttpMethod_GET  HttpMethod = 0
	HttpMethod_POST HttpMethod = 1
)

var HttpMethod_name = map[int32]string{
	0: "GET",
	1: "POST",
}

var HttpMethod_value = map[string]int32{
	"GET":  0,
	"POST": 1,
}

func (x HttpMethod) String() string {
	return proto.EnumName(HttpMethod_name, int32(x))
}

func (HttpMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_904d21d0f6a3122c, []int{0}
}

type RequestContentType int32

const (
	RequestContentType_APPLICATION_X_WWW_FORM_URLENCODED RequestContentType = 0
	RequestContentType_MULTIPART_FORM_DATA               RequestContentType = 1
	RequestContentType_APPLICATION_JSON                  RequestContentType = 2
)

var RequestContentType_name = map[int32]string{
	0: "APPLICATION_X_WWW_FORM_URLENCODED",
	1: "MULTIPART_FORM_DATA",
	2: "APPLICATION_JSON",
}

var RequestContentType_value = map[string]int32{
	"APPLICATION_X_WWW_FORM_URLENCODED": 0,
	"MULTIPART_FORM_DATA":               1,
	"APPLICATION_JSON":                  2,
}

func (x RequestContentType) String() string {
	return proto.EnumName(RequestContentType_name, int32(x))
}

func (RequestContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_904d21d0f6a3122c, []int{1}
}

type RequestFile struct {
	Reader               string   `protobuf:"bytes,1,opt,name=reader,proto3" json:"reader,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFile) Reset()         { *m = RequestFile{} }
func (m *RequestFile) String() string { return proto.CompactTextString(m) }
func (*RequestFile) ProtoMessage()    {}
func (*RequestFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_904d21d0f6a3122c, []int{0}
}

func (m *RequestFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFile.Unmarshal(m, b)
}
func (m *RequestFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFile.Marshal(b, m, deterministic)
}
func (m *RequestFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFile.Merge(m, src)
}
func (m *RequestFile) XXX_Size() int {
	return xxx_messageInfo_RequestFile.Size(m)
}
func (m *RequestFile) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFile.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFile proto.InternalMessageInfo

func (m *RequestFile) GetReader() string {
	if m != nil {
		return m.Reader
	}
	return ""
}

func (m *RequestFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

var E_FieldMethod = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*HttpMethod)(nil),
	Field:         1000,
	Name:          "rest.field_method",
	Tag:           "varint,1000,opt,name=field_method,enum=rest.HttpMethod",
	Filename:      "extend.proto",
}

var E_Name = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1001,
	Name:          "rest.name",
	Tag:           "bytes,1001,opt,name=name",
	Filename:      "extend.proto",
}

var E_Required = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1002,
	Name:          "rest.required",
	Tag:           "varint,1002,opt,name=required",
	Filename:      "extend.proto",
}

var E_Path = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1000,
	Name:          "rest.path",
	Tag:           "bytes,1000,opt,name=path",
	Filename:      "extend.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*HttpMethod)(nil),
	Field:         1001,
	Name:          "rest.method",
	Tag:           "varint,1001,opt,name=method,enum=rest.HttpMethod",
	Filename:      "extend.proto",
}

var E_Url = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1002,
	Name:          "rest.url",
	Tag:           "bytes,1002,opt,name=url",
	Filename:      "extend.proto",
}

var E_NoCookie = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1003,
	Name:          "rest.no_cookie",
	Tag:           "varint,1003,opt,name=no_cookie",
	Filename:      "extend.proto",
}

var E_RequestContentType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*RequestContentType)(nil),
	Field:         1004,
	Name:          "rest.request_content_type",
	Tag:           "varint,1004,opt,name=request_content_type,enum=rest.RequestContentType",
	Filename:      "extend.proto",
}

func init() {
	proto.RegisterEnum("rest.HttpMethod", HttpMethod_name, HttpMethod_value)
	proto.RegisterEnum("rest.RequestContentType", RequestContentType_name, RequestContentType_value)
	proto.RegisterType((*RequestFile)(nil), "rest.RequestFile")
	proto.RegisterExtension(E_FieldMethod)
	proto.RegisterExtension(E_Name)
	proto.RegisterExtension(E_Required)
	proto.RegisterExtension(E_Path)
	proto.RegisterExtension(E_Method)
	proto.RegisterExtension(E_Url)
	proto.RegisterExtension(E_NoCookie)
	proto.RegisterExtension(E_RequestContentType)
}

func init() { proto.RegisterFile("extend.proto", fileDescriptor_904d21d0f6a3122c) }

var fileDescriptor_904d21d0f6a3122c = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x5f, 0x6b, 0xd4, 0x40,
	0x14, 0xc5, 0x9b, 0x36, 0xec, 0x9f, 0xdb, 0x22, 0x61, 0x2c, 0x1a, 0x04, 0x75, 0x15, 0x84, 0xd2,
	0x87, 0x14, 0xdb, 0x27, 0x07, 0x5f, 0x42, 0x76, 0x57, 0x23, 0xbb, 0x9b, 0x30, 0x9b, 0xb2, 0xbe,
	0x0d, 0xdb, 0xcd, 0x6d, 0x1b, 0x9b, 0x66, 0xd2, 0xc9, 0x04, 0xf4, 0x1b, 0xbb, 0xab, 0x1f, 0x42,
	0x92, 0x89, 0xae, 0xb2, 0x48, 0xde, 0x32, 0x77, 0xee, 0x39, 0x39, 0xbf, 0xe1, 0xc0, 0x11, 0x7e,
	0x55, 0x98, 0xc5, 0x4e, 0x2e, 0x85, 0x12, 0xc4, 0x94, 0x58, 0xa8, 0x67, 0x83, 0x1b, 0x21, 0x6e,
	0x52, 0x3c, 0xab, 0x67, 0x57, 0xe5, 0xf5, 0x59, 0x8c, 0xc5, 0x4a, 0x26, 0xb9, 0x12, 0x52, 0xef,
	0xbd, 0x7e, 0x07, 0x87, 0x0c, 0x1f, 0x4a, 0x2c, 0xd4, 0x38, 0x49, 0x91, 0x3c, 0x81, 0x8e, 0xc4,
	0x65, 0x8c, 0xd2, 0x36, 0x06, 0xc6, 0x49, 0x9f, 0x35, 0x27, 0x42, 0xc0, 0xcc, 0x96, 0xf7, 0x68,
	0xef, 0xd7, 0xd3, 0xfa, 0xfb, 0xf4, 0x25, 0xc0, 0x47, 0xa5, 0xf2, 0x29, 0xaa, 0x5b, 0x11, 0x93,
	0x2e, 0x1c, 0x7c, 0x18, 0x45, 0xd6, 0x1e, 0xe9, 0x81, 0x19, 0x06, 0xf3, 0xc8, 0x32, 0x4e, 0xbf,
	0x00, 0x69, 0xbc, 0x3d, 0x91, 0x29, 0xcc, 0x54, 0xf4, 0x2d, 0x47, 0xf2, 0x06, 0x5e, 0xb9, 0x61,
	0x38, 0xf1, 0x3d, 0x37, 0xf2, 0x83, 0x19, 0xff, 0xcc, 0x17, 0x8b, 0x05, 0x1f, 0x07, 0x6c, 0xca,
	0x2f, 0xd9, 0x64, 0x34, 0xf3, 0x82, 0xe1, 0x68, 0x68, 0xed, 0x91, 0xa7, 0xf0, 0x78, 0x7a, 0x39,
	0x89, 0xfc, 0xd0, 0x65, 0x91, 0xbe, 0x1e, 0xba, 0x91, 0x6b, 0x19, 0xe4, 0x18, 0xac, 0xbf, 0xf5,
	0x9f, 0xe6, 0xc1, 0xcc, 0xda, 0xa7, 0x73, 0x38, 0xba, 0x4e, 0x30, 0x8d, 0xf9, 0xbd, 0x8e, 0xf3,
	0xdc, 0xd1, 0xe8, 0xce, 0x6f, 0x74, 0x67, 0x5c, 0x5d, 0x07, 0xb9, 0x4a, 0x44, 0x56, 0xd8, 0xdf,
	0xbb, 0x03, 0xe3, 0xe4, 0xd1, 0xb9, 0xe5, 0x54, 0xcf, 0xe4, 0x6c, 0x31, 0xd8, 0x61, 0xed, 0xa2,
	0x0f, 0xf4, 0x5c, 0x53, 0xb7, 0x99, 0xad, 0xbb, 0xdb, 0x57, 0xa1, 0x14, 0x7a, 0x12, 0x1f, 0xca,
	0x44, 0x62, 0x6b, 0x88, 0x4d, 0xa5, 0xeb, 0xb1, 0x3f, 0xfb, 0xf4, 0x02, 0xcc, 0x7c, 0xa9, 0x6e,
	0xc9, 0x8b, 0x1d, 0x9d, 0x0e, 0xf4, 0x4f, 0xfa, 0x3e, 0xab, 0x97, 0xa9, 0x0f, 0x9d, 0x86, 0xb9,
	0x4d, 0xb6, 0xfe, 0x1f, 0x74, 0x63, 0x40, 0xdf, 0xc2, 0x41, 0x29, 0xd3, 0x56, 0x9f, 0x8d, 0xfe,
	0x7d, 0xb5, 0x4b, 0xdf, 0x43, 0x3f, 0x13, 0x7c, 0x25, 0xc4, 0x5d, 0x82, 0xad, 0xc2, 0x1f, 0x0d,
	0x70, 0x26, 0xbc, 0x5a, 0x40, 0xef, 0xe0, 0x58, 0xea, 0x86, 0xf0, 0x95, 0xae, 0x08, 0x57, 0x55,
	0x47, 0xda, 0x8c, 0x7e, 0x6a, 0x12, 0x5b, 0x93, 0xec, 0x96, 0x8c, 0x11, 0xb9, 0x33, 0xbb, 0xea,
	0xd4, 0x66, 0x17, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x18, 0x69, 0x30, 0x6c, 0x29, 0x03, 0x00,
	0x00,
}
